# Generated by Django 5.2.5 on 2025-08-15 12:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_address_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (recommended size: 300x300px)', null=True, upload_to=core.models.user_avatar_path),
        ),
    ]
